AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Configure the CyngularCloudFormationStackSetExecutionRole to enable use of your account as a target account in AWS CloudFormation StackSets.

Parameters:
  AdministratorAccountId:
    Type: 'String'
    Description: 'AWS Account Id of the administrator account (the account in which StackSets will be created).'
    MaxLength: 12
    MinLength: 12

Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'CyngularCloudFormationStackSetExecutionRole'
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref AdministratorAccountId
              Service: 'cloudformation.amazonaws.com'
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/AdministratorAccess'

      Tags:
        - Key: Vendor
          Value: "Cyngular Security"
        - Key: CFNRegion
          Value: !Ref 'AWS::Region'