AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Stack - 2
  1. Applied on Management account per region
  2. Applied on all client child accounts per region

Parameters:
  CyngularAccountId:
    Description: "Cyngular AWS Account ID to assume the read only role [851565895544]"
    Type: String
    # Default: "851565895544"
    # AllowedValues: ["851565895544"]

Resources:
  CyngularKmsKey:
    Type: AWS::KMS::Key
    Properties:
      Description: cyngular_kms_key
      KeyPolicy:
        Id: key-policy-1
        Version: "2012-10-17"
        Statement:
          - Sid: "Enable IAM User Permissions"
            Effect: Allow
            Principal:
              AWS:
                - !Sub "arn:aws:iam::${AWS::AccountId}:root"                
                - !Sub "arn:aws:iam::${CyngularAccountId}:root"     
            Action: "kms:*"
            Resource: "*"

      Tags:
        - Key: Name
          Value: cyngular-kms-key

  CyngularKmsAlias:
    Type: AWS::KMS::Alias
    DependsOn: CyngularKmsKey
    Properties: 
      AliasName: alias/cyngular-kms-key
      TargetKeyId: !GetAtt CyngularKmsKey.Arn