AWSTemplateFormatVersion: 2010-09-09
Description: >-
  StackSet - 1
  Applied on all client accounts in one region

Parameters:
  ClientName:
    Description: "The name of the client. (must be lowercase, can contain letters, numbers and dashes)"
    Type: "String"
    AllowedPattern: "^[a-z0-9]+$"
    MinLength: 3
    MaxLength: 10
    Default: ""

  CyngularAccountId:
    Description: "Cyngular AWS Account id"
    Type: String
    Default: "851565895544"
    AllowedValues: ["851565895544"]

  S3BucketArn:
    Description: The Arn of the Cyngular Managed S3 Bucket.
    Type: String
    
Resources:
  ClientCyngularRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "cyngular-readonly-role-${ClientName}"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${CyngularAccountId}:root"
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: cyngular-readonly-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: readOnly
                Effect: Allow
                Resource: '*'
                Action:
                  - iam:List*
                  - iam:Get*
                  - iam:GenerateServiceLastAccessedDetails

                  - organizations:Describe*
                  - organizations:List*

                  - ce:List*
                  - ce:Get*
                  - ce:Describe*

                  - s3:List*
                  - s3:Describe*
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
                  - s3:GetBucketPolicy
                  - s3:GetBucketPolicyStatus
                  - s3:GetEncryptionConfiguration
                  - s3:GetAccountPublicAccessBlock
                  - s3:GetBucketPublicAccessBlock

                  - logs:List*
                  - logs:Describe*
                  - logs:Get*
                  - logs:FilterLogEvents
                  - logs:StartQuery

                  - ec2:List*
                  - ec2:CreateTags
                  - ec2:Describe*
                  - ec2:GetImageBlockPublicAccessState

                  - ecr:Describe*
                  - ecr:List*

                  - eks:Describe*
                  - eks:List*

                  - ecs:List*
                  - ecs:Describe*

                  - lambda:List*
                  - lambda:Get*
                  - rds:List*
                  - rds:Describe*

                  - cloudformation:Describe*
                  - cloudformation:List*
                  - cloudformation:Get*
                  
                  - tag:GetResources

                  - route53:Get*
                  - route53:List*
                  - route53:TestDNSAnswer

                  - route53resolver:List*
                  - route53resolver:Get*

                  - cloudtrail:Get*
                  - cloudtrail:Describe*
                  - cloudtrail:List*
                  - cloudtrail:LookupEvents

                  - kms:Describe*
                  - kms:Get*
                  - kms:List*

                  - events:List*
                  - events:Describe*

                  - cloudwatch:ListMetrics
                  - cloudwatch:GetMetricData
                  - cloudwatch:GetMetricStatistics

              - Sid: ec2CyngularSnapshot
                Effect: Allow
                Action:
                  - ec2:DeleteSnapshot
                  - ec2:ModifySnapshotAttribute
                Resource: '*'
                Condition:
                  StringLike:
                    aws:ResourceTag/Name: cyngular*

              - Sid: ec2CreateSnapshot
                Effect: Allow
                Resource: '*'
                Action:
                  - ec2:CopySnapshot
                  - ec2:CreateSnapshot
                  - ec2:CreateSnapshots

              - Sid: CyngularBucketAdmin
                Effect: Allow
                Resource:
                  - !Ref S3BucketArn
                  - !Sub "${S3BucketArn}/*"
                Action:
                  - "s3:*"

              - Sid: KmsPartial
                Effect: Allow
                Resource: '*'
                Action:
                  - kms:Decrypt
                  - kms:CreateGrant

              - Sid: CyngularKmsKey
                Effect: Allow
                Resource: '*'
                Action:
                  - kms:*
                Condition:
                  StringLike:
                    aws:ResourceTag/Name: cyngular*

              - Sid: "ListRegionsOnAccounts"
                Effect: "Allow"
                Action:
                  - "account:ListRegions"
                Resource:
                  - arn:aws:account::*:account/o-*/*
                  - arn:aws:account::*:account