AWSTemplateFormatVersion: 2010-09-09

Description: |-
  Cyngular Core Infrastructure Template
  Creates: S3 bucket (cyngular-{client}-bucket-{account}), S3 bucket policy (CloudTrail/Cyngular access),
  IAM role policy (readonly S3 access), CloudTrail trail (conditional audit logging),

Metadata:
  Vendor:
    Description: "Cyngular Security"

  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Client Info"
        Parameters:
          - ClientName
      - Label:
          default: "Override Parameters"
        Parameters:
          - EnableCloudTrail
          - OrganizationId

Mappings:
  Const:
    "Cyngular":
      LambdasBucketPrefix: "cyngular-onboarding"
      PythonRuntime: "python3.12"
      DeletionPolicy: "Retain"
      SSEAlgorithm: "AES256"
      LifecycleStandardIADays: 60
      LifecycleGlacierDays: 90
      LifecycleExpirationDays: 365
      LayerName: "cyngular-onboarding-layer"
      CodeVersion: "latest"
      CyngularDefaultAccountId: "851565895544"
      TrailName: "cyngular-cloudtrail"

Parameters:
  ClientName:
    Description: "The Client Company name (must be lowercase, can contain letters & numbers)"
    Type: String
    AllowedPattern: "^[a-z0-9]+$"
    ConstraintDescription: "Company Name should consist of only lowercase characters and numbers, and it should not start with a number."
    MinLength: 3
    MaxLength: 15

  OrganizationId:
    Description: "Specify the Company Organization id | leave empty if not deploying to an organization"
    Type: String

  EnableCloudTrail:
    Description: "Create Cyngular Trail | set to false to disable"
    Type: String
    AllowedValues: ["true", "false"]
    Default: "true"

Conditions:
  IsOrg: !Not [!Equals [!Ref OrganizationId, ""]]
  CreateCloudTrail: !Equals [!Ref EnableCloudTrail, "true"]

Resources:
  ################################################################################
  # STORAGE - S3 Bucket for Security Logs Collection
  ################################################################################
  CyngularS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: !FindInMap [Const, Cyngular, DeletionPolicy]
    UpdateReplacePolicy: !FindInMap [Const, Cyngular, DeletionPolicy]
    Properties:
      BucketName: !Sub "cyngular-${ClientName}-bucket-${AWS::AccountId}"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: !FindInMap [Const, Cyngular, SSEAlgorithm]
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

      LifecycleConfiguration:
        Rules:
          ## transitions objects to Standard-IA after 60 days
          ## Glacier after 90 days
          ## deletes them after a year
          - Id: ObjectLifecycleRule
            Status: Enabled
            Transitions:
              - TransitionInDays:
                  !FindInMap [Const, Cyngular, LifecycleStandardIADays]
                StorageClass: STANDARD_IA
              - TransitionInDays:
                  !FindInMap [Const, Cyngular, LifecycleGlacierDays]
                StorageClass: GLACIER
            ExpirationInDays:
              !FindInMap [Const, Cyngular, LifecycleExpirationDays]

      Tags:
        - Key: Name
          Value: !Sub "cyngular-${ClientName}-bucket-${AWS::AccountId}"
        - Key: cyngular-os
          Value: true
        - Key: cyngular-visibility
          Value: true
        - Key: ClientName
          Value: !Ref ClientName
        - !If
          - CreateCloudTrail
          - Key: cyngular-cloudtrail
            Value: "true"
          - !Ref AWS::NoValue

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CyngularS3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "CyngularAdmin"
            Effect: Allow
            Principal:
              AWS:
                - !Sub "arn:aws:iam::${AWS::AccountId}:root"
                - !Sub
                  - "arn:aws:iam::${cyngular_account_id}:root"
                  - cyngular_account_id:
                      Fn::ImportValue:
                        !Join [
                          ":",
                          [
                            "CyngularSecurity",
                            "CyngularAccountId",
                            !Ref ClientName,
                          ],
                        ]

            Action:
              - "s3:*"
            Resource:
              - !GetAtt CyngularS3Bucket.Arn
              - !Sub "arn:aws:s3:::${CyngularS3Bucket}/*"

          - !If
            - CreateCloudTrail
            - Sid: "CloudTrailAclCheck"
              Effect: Allow
              Principal:
                Service: "cloudtrail.amazonaws.com"
              Action: "s3:GetBucketAcl"
              Resource: !GetAtt CyngularS3Bucket.Arn
              Condition:
                StringEquals:
                  AWS:SourceArn: !Sub "arn:aws:cloudtrail:${AWS::Region}:${AWS::AccountId}:trail/cyngular-cloudtrail"
            - !Ref "AWS::NoValue"
          - !If
            - CreateCloudTrail
            - Sid: "CloudTrailWrite"
              Effect: Allow
              Principal:
                Service: "cloudtrail.amazonaws.com"
              Action:
                - "s3:PutObject"
              Resource:
                - !Sub "arn:aws:s3:::${CyngularS3Bucket}/AWSLogs/${AWS::AccountId}/*"
                - !If
                  - IsOrg
                  - !Sub "arn:aws:s3:::${CyngularS3Bucket}/AWSLogs/${OrganizationId}/*"
                  - !Ref "AWS::NoValue"
              Condition:
                StringEquals:
                  s3:x-amz-acl: "bucket-owner-full-control"
                  AWS:SourceArn: !Sub "arn:aws:cloudtrail:${AWS::Region}:${AWS::AccountId}:trail/cyngular-cloudtrail"
            - !Ref "AWS::NoValue"

  ##############################
  # Cyngular Bucket Access Policy
  ##############################
  CyngularBucketAccessPolicy:
    Type: AWS::IAM::RolePolicy
    Properties:
      PolicyName: !Sub "cyngular-bucket-access-policy-${ClientName}"
      RoleName:
        Fn::ImportValue:
          !Join [":", ["CyngularSecurity", "ReadonlyRoleName", !Ref ClientName]]
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "CyngularBucketAdmin"
            Effect: Allow
            Resource:
              - !GetAtt CyngularS3Bucket.Arn
              - !Sub "arn:aws:s3:::${CyngularS3Bucket}/*"
            Action:
              - "s3:*"

  ##############################
  # Cyngular CloudTrail
  ##############################
  ClientCloudTrail:
    DependsOn: S3BucketPolicy
    Condition: CreateCloudTrail
    Type: AWS::CloudTrail::Trail
    Properties:
      TrailName: !FindInMap [Const, Cyngular, TrailName]
      S3BucketName: !Ref CyngularS3Bucket
      InsightSelectors:
        - InsightType: ApiCallRateInsight
        - InsightType: ApiErrorRateInsight
      EventSelectors:
        - IncludeManagementEvents: true
          ExcludeManagementEventSources:
            - kms.amazonaws.com
          DataResources:
            - Type: AWS::Lambda::Function
              Values:
                - arn:aws:lambda
      IsLogging: true
      IsMultiRegionTrail: true
      IsOrganizationTrail: !If [IsOrg, true, false]
      IncludeGlobalServiceEvents: true
      Tags:
        - Key: Name
          Value: cyngular-cloudtrail
        - Key: ClientName
          Value: !Ref ClientName

##############################
# Outputs
##############################
Outputs:
  CyngularBucketName:
    Description: "Name of the Cyngular S3 bucket"
    Value: !Ref CyngularS3Bucket
    Export:
      Name:
        !Join [
          ":",
          ["CyngularSecurity", "CyngularSecurityBucketName", !Ref ClientName],
        ]

  IsOrganization:
    Description: Whether this is an organization deployment
    Value: !If [IsOrg, "true", "false"]
    Export:
      Name: !Join [":", ["CyngularSecurity", "IsOrganization", !Ref ClientName]]
