AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Configure the CyngularCloudFormationStackSetAdministrationRole to enable use of AWS CloudFormation StackSets.

Resources:
  AdministrationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CyngularCloudFormationStackSetAdministrationRole
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 'cloudformation.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: AssumeRole-CyngularCloudFormationStackSetExecutionRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'sts:AssumeRole'
                Resource:
                  - !Sub 'arn:${AWS::Partition}:iam::*:role/CyngularCloudFormationStackSetExecutionRole'
      Tags:
        - Key: Vendor
          Value: "Cyngular Security"
        - Key: CFNRegion
          Value: !Ref 'AWS::Region'