AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  Stack - 2
  Applied on Management account per region
  
Parameters:
  CyngularAccountId:
    Description: "The Cyngular account id"
    Type: String

Resources:
  CyngularKmsKey:
    Type: AWS::KMS::Key
    Properties: 
      Description: cyngular_kms_key
      KeyPolicy:
        Id: key-policy-1
        Version: "2012-10-17"
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS:
                - !Sub "arn:aws:iam::${CyngularAccountId}:root"
                - !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"

      Tags: 
        - Key: Name
          Value: cyngular-kms-key

  CyngularKmsAlias:
    Type: AWS::KMS::Alias
    Properties: 
      AliasName: alias/cyngular-kms-key
      TargetKeyId: !GetAtt CyngularKmsKey.Arn