AWSTemplateFormatVersion: "2010-09-09"
Description: Multiple route53 resolvers in multiple regions

Parameters:
  CyngularAccountId:
    Description: The cyngular account id
    Type: String
  ClientRegions:
    Type: CommaDelimitedList
  S3BucketArn:
    Type: String
  EnableDNS:
    Description: "DNS Service - Whether to Create Route 53 Resolver, for vpc flows logs"
    Type: String

Conditions:
  ServiceDNS: !Equals [ !Ref EnableDNS, "true" ]

Resources:
  CyngularKmsKey:
    Type: AWS::KMS::Key
    Properties: 
      Description: cyngular_kms_key
      KeyPolicy:
        Id: key-policy-1
        Version: "2012-10-17"
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS:
                - !Sub "arn:aws:iam::${CyngularAccountId}:root"
                - !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"              

      Tags: 
        - Key: Name
          Value: cyngular-kms-key

  CyngularKmsAlias:
    Type: AWS::KMS::Alias
    Properties: 
      AliasName: alias/cyngular-kms-key
      TargetKeyId: !GetAtt CyngularKmsKey.Arn

  CyngularResolver:
    Type: AWS::Route53Resolver::ResolverQueryLoggingConfig
    Condition: ServiceDNS
    Properties: 
      DestinationArn: !Ref S3BucketArn
      Name: cyngular_dns