AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ClientName:
    Description: "The name of the client. (must be lowercase, can contain letters, numbers and dashes)"
    Type: "String"
    MinLength: 3
    MaxLength: 15

Resources:
  CyngularReadOnlyPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: "cyngular-readonly-policy-v3"
      Roles:
        - !Sub "cyngular-readonly-role-${ClientName}"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: readOnly
            Effect: Allow
            Resource: '*'
            Action:
              - iam:List*
              - iam:Get*
              - iam:GenerateServiceLastAccessedDetails

              - organizations:Describe*
              - organizations:List*
              - organizations:EnableAWSServiceAccess
              - organizations:RegisterDelegatedAdministrator

              - cloudtrail:LookupEvents
              - kms:List*
              - kms:Describe*
              - s3:List*
              - s3:Describe*
              - s3:GetBucketAcl
              - s3:GetBucketLocation
              - s3:GetBucketPolicyStatus
              - s3:GetEncryptionConfiguration

              - s3:GetAccountPublicAccessBlock
              - s3:GetBucketPublicAccessBlock

              - logs:List*
              - logs:Describe*
              - logs:Get*
              - logs:FilterLogEvents
              - logs:StartQuery
              - cloudwatch:GetMetricStatistics

              - ec2:List*
              - ec2:CreateTags
              - ec2:Describe*
              - ecr:Describe*
              - ecr:List*
              - eks:Describe*
              - eks:List*
              - ecs:List*
              - ecs:Describe*
              - lambda:List*
              - lambda:Get*
              - rds:List*
              - rds:Describe*

              - cloudformation:Describe*
              - cloudformation:List*
              - cloudformation:Get*
              
              - tag:GetResources

          - Sid: ec2CyngularSnapshot
            Effect: Allow
            Action:
              - ec2:DeleteSnapshot
              - ec2:ModifySnapshotAttribute
            Resource: '*'
            Condition:
              StringLike:
                aws:ResourceTag/Name: cyngular*
          - Sid: ec2CreateSnapshot
            Effect: Allow
            Resource: '*'
            Action:
              - ec2:CopySnapshot
              - ec2:CreateSnapshot
              - ec2:CreateSnapshots
          - Sid: CyngularBucketAdmin
            Effect: Allow
            Resource:
              - !Sub "arn:aws:s3:::cyngular-${ClientName}-bucket-${AWS::AccountId}"
              - !Sub "arn:aws:s3:::cyngular-${ClientName}-bucket-${AWS::AccountId}/*"

            Action:
              - "s3:*"
          - Sid: KmsPartial
            Effect: Allow
            Resource: '*'
            Action:
              - kms:Decrypt
              - kms:CreateGrant
          - Sid: CyngularKmsKey
            Effect: Allow
            Resource: '*'
            Action:
              - kms:*
            Condition:
              StringLike:
                aws:ResourceTag/Name: cyngular*
          - Sid: "ListRegionsOnAccounts"
            Effect: "Allow"
            Action:
              - "account:ListRegions"
            Resource:
              - arn:aws:account::*:account/o-*/*
              - arn:aws:account::*:account