AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Cyngular Gen3 Lambda Layer - Shared utilities and dependencies for Gen3 Lambda functions

Transform:
  - 'AWS::LanguageExtensions'

Metadata:
  Vendor:
    Description: Cyngular Security

  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Layer"
        Parameters:
          - LayerName
          - LayerDescription
          - CompatibleRuntimes
          - LicenseInfo

Mappings:
  VARS:
    "Cyngular":
      LambdasBucketPrefix: "cyngular-onboarding"

Parameters:
  LayerName:
    Type: String
    Default: 'cyngular-common'
    Description: 'Name for the Lambda layer'
    AllowedPattern: '^[a-zA-Z0-9-_]+$'
    ConstraintDescription: 'Layer name must contain only alphanumeric characters, hyphens, and underscores'

  LayerDescription:
    Type: String
    Default: 'Shared utilities and dependencies for Cyngular Gen3 Lambda functions'
    Description: 'Description for the Lambda layer'

  CompatibleRuntimes:
    Type: CommaDelimitedList
    Default: 'python3.9,python3.10,python3.11,python3.12,python3.13'
    Description: 'Compatible Python runtimes for the layer'

  LicenseInfo:
    Type: String
    # Default: 'MIT'
    Default: ''
    Description: 'License information for the layer'

Resources:
  CyngularGen3Layer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: !Ref LayerName
      Description: !Ref LayerDescription
      Content:
        S3Bucket: !Sub
          - "${bucket_name}-${AWS::Region}"
          - bucket_name: !FindInMap [VARS, Cyngular, LambdasBucketPrefix]
        S3Key: !Sub 'layers/${LayerName}/layer.zip'
      CompatibleRuntimes: !Ref CompatibleRuntimes
      LicenseInfo: !Ref LicenseInfo
      CompatibleArchitectures:
        - x86_64
        - arm64

  LayerVersionPermission:
    Type: AWS::Lambda::LayerVersionPermission
    Properties:
      LayerVersionArn: !Ref CyngularGen3Layer
      Action: lambda:GetLayerVersion
      Principal: "*"
      # Principal: !Ref AWS::AccountId
      OrganizationId: !Ref AWS::NoValue

Outputs:
  LayerArn:
    Description: 'ARN of the Cyngular Gen3 Lambda Layer'
    Value: !Ref CyngularGen3Layer
    Export:
      Name: !Sub '${AWS::StackName}-LayerArn'

  LayerVersion:
    Description: 'Version number of the Lambda Layer'
    Value: !GetAtt CyngularGen3Layer.Version
    Export:
      Name: !Sub '${AWS::StackName}-LayerVersion'

  LayerName:
    Description: 'Name of the Lambda Layer'
    Value: !Ref LayerName
    Export:
      Name: !Sub '${AWS::StackName}-LayerName'