AWSTemplateFormatVersion: "2010-09-09"
Description: Stackset for multiple route53 resolvers and guardduty detectors

Parameters:
  ClientName:
    Type: String
    Description: The name of the client
  deployRegions:
    Type: CommaDelimitedList
    Description: The regions in which the client operates (use ,)
  S3ManagementBucketArn:
    Description: The Arn of the created S3 bucket.
    Type: String
  CyngularAccountId:
    Description: The cyngular account id
    Type: String
    Default: 851565895544
Resources:
  StackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      Description: Multiple route53 resolvers and guardduty detectors in multiple regions
      PermissionModel: SELF_MANAGED
      Parameters:
        - ParameterKey: ClientName
          ParameterValue: !Ref ClientName
        - ParameterKey: S3ManagementBucketArn
          ParameterValue: !Ref S3ManagementBucketArn
        - ParameterKey: CyngularAccountId
          ParameterValue: !Ref CyngularAccountId

      StackInstancesGroup:
        - DeploymentTargets:
            Accounts:
              - !Ref "AWS::AccountId"
          Regions: !Ref deployRegions

      StackSetName: !Sub "cyngular-stack-${ClientName}"
      TemplateBody: !Sub |
        AWSTemplateFormatVersion: 2010-09-09
        Description: Create a guardduty detector and route53 resolver
        Parameters:
          ClientName:
            Type: String
          S3ManagementBucketArn:
            Type: String
          CyngularAccountId:
            Description: The cyngular account id
            Type: String
        Resources:
          #------------------Cyngular KMS Key-------------------
          CyngularKmsKey:
            Type: AWS::KMS::Key
            Properties: 
              Description: cyngular_kms_key
              KeyPolicy: {
                "Id" : "key-consolepolicy-3",
                "Version" : "2012-10-17",
                "Statement" : [
                    {
                        "Sid" : "Enable IAM User Permissions",
                        "Effect" : "Allow",
                        "Principal" : {
                            "AWS": [
                                !Join [ '', ['arn:aws:iam::', !Ref CyngularAccountId, ':root']],
                                !Join [ '', ['arn:aws:iam::', !Ref AWS::AccountId, ':root']] 
                            ]
                        },
                        "Action" : "kms:*",
                        "Resource" : "*"
                    }
                ]
            }
              Tags: 
                - Key: Name
                  Value: cyngular-kms-key
          
          CyngularKmsAlias:
            DependsOn: CyngularKmsKey
            Type: AWS::KMS::Alias
            Properties: 
                AliasName: alias/cyngular-kms-key
                TargetKeyId: !GetAtt  CyngularKmsKey.Arn
          CyngularResolver:
            Type: AWS::Route53Resolver::ResolverQueryLoggingConfig
            Properties: 
              DestinationArn: !Ref S3ManagementBucketArn
              Name: cyngular_dns
