AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Cyngular OnBoarding stack template

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Cyngular Info"
        Parameters:
          - CyngularAccountId

    ParameterLabels:
      CyngularAccountId:
        default: "Cyngular Account Id"

Parameters:
  CyngularAccountId:
    Description: The cyngular account id
    Type: String
    Default: "851565895544"

Resources:
  CyngularKmsKey:
    Type: AWS::KMS::Key
    Properties: 
      Description: cyngular_kms_key
      KeyPolicy:
        Id: key-policy-1
        Version: "2012-10-17"
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS:
                - !Sub "arn:aws:iam::${CyngularAccountId}:root"
                - !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"
      Tags: 
        - Key: Name
          Value: cyngular-kms-key
  
  CyngularKmsAlias:
    Type: AWS::KMS::Alias
    Properties: 
      AliasName: alias/cyngular-kms-key
      TargetKeyId: !GetAtt CyngularKmsKey.Arn