name: Python Code Quality

on:
  push:
    branches: [ main, dev, "release/*" ]
    paths:
      - 'Lambdas/**/*.py'
      - '.github/workflows/python-test.yml'
  pull_request:
    branches: [ main, dev, "release/*" ]
    paths:
      - 'Lambdas/**/*.py'
      - '.github/workflows/python-test.yml'

jobs:
  python-quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff bandit
    
    - name: Run Ruff Check
      run: |
        echo "Running Ruff code quality checks..."
        ruff check Lambdas/
    
    - name: Run Bandit Security Check
      run: |
        echo "Running Bandit security analysis..."
        bandit -r Lambdas/ -f json -o bandit-report.json || true
        
        # Display JSON report content
        if [ -f bandit-report.json ] && [ -s bandit-report.json ]; then
          echo "📊 Bandit Security Report:"
          cat bandit-report.json | jq '.'
          
          # Check for HIGH severity issues and fail if found
          HIGH_COUNT=$(cat bandit-report.json | jq '.results[] | select(.issue_severity == "HIGH") | .issue_severity' | wc -l)
          if [ "$HIGH_COUNT" -gt 0 ]; then
            echo "❌ Found $HIGH_COUNT HIGH severity security issues"
            exit 1
          else
            echo "✅ No HIGH severity security issues found"
          fi
        else
          echo "⚠️  No bandit report generated or file is empty"
        fi
    
    - name: Upload Bandit Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: bandit-security-report
        path: bandit-report.json
        retention-days: 30